#!/bin/bash


# Create ".chrom" and ".GT" files

# MODIFIED SCRIPT STEP1
# --------------------------------------------------------------------------------------->

# source ./args_for_step1_step2_inference_bash_file
chrom_no_missing="${scaffold_name}_no_missing.vcf.gz"
all_markers=`bcftools query -f '%POS\n' ${chrom_no_missing}`
total_markers_vcf=`echo "${all_markers}" | wc -l `
window_length=`echo ${recom_freq}*$((10**6))/${recom_rate} | bc -l`
window_length=`echo "${window_length}/1" | bc`

leftmost_marker=`echo "${all_markers}" | sed -n '1p'`
last_marker=`echo "${all_markers}" | tail -1`
# echo ${last_marker}
theoretical_rightmost_marker=`echo ${last_marker}-${window_length} | bc -l`
# echo ${theoretical_rightmost_marker}
empirical_rightmost_marker=`echo "${all_markers}" | awk -v c=1 -v t=${theoretical_rightmost_marker} 'NR==1{d=$c-t;d=d<0?-d:d;v=$c;next}{m=$c-t;m=m<0?-m:m}m<d{d=m;v=$c}m>d{exit}END{print v}'`
number_windows=`echo "${all_markers}" | grep -n ${empirical_rightmost_marker} | awk -F: '{print $1}'`


# echo ${window_index}
first_marker=`echo "${all_markers}" | sed -n "${window_index}p"`
# echo ${first_marker}
inter_marker_distance=$(echo "${window_length}/$(( ${n_markers}-1 ))" | bc -l)
inter_marker_distance=`echo "${inter_marker_distance}/1" | bc`
# echo ${inter_marker_distance}
theoretical_markers=()
for ((i=0; i<= ${n_markers}-1; i++))
do
    m=$(echo "${first_marker}+$i*${inter_marker_distance}" | bc)
    theoretical_markers+=( $m )
done


chrom_filename="${scaffold_name}_w${window_index}.chrom"
chrom_info=`echo "1"$'\t'${scaffold_length}$'\t'${recom_rate}$'\t'${n_markers}`
empirical_markers=()
for j in ${theoretical_markers[@]}
do
    m1=`echo "${all_markers}" | awk -v c=1 -v t=$j 'NR==1{d=$c-t;d=d<0?-d:d;v=$c;next}{m=$c-t;m=m<0?-m:m}m<d{d=m;v=$c}m>d{exit}END{print v}'`
    chrom_info+=`echo $'\t'$m1`
    empirical_markers+=( ${scaffold_name}:$m1 )
done

echo "${chrom_info}" > ${chrom_filename}


#-------------------------------------------------------->


BO_genotype_file="BO_${scaffold_name}_w${window_index}.GT"
SO_genotype_file="SO_${scaffold_name}_w${window_index}.GT"
hybrid_genotype_file="hybrid_${scaffold_name}_w${window_index}.GT"

header_BO="chrom:pos"
while read indv
do
    header_BO+=`echo $'\t'${indv}`
done < ${BO_filename}
echo "${header_BO}" > ${BO_genotype_file}

header_SO="chrom:pos"
while read indv
do
    header_SO+=`echo $'\t'${indv}`
done < ${SO_filename}
echo "${header_SO}" > ${SO_genotype_file}

header_hybrid="chrom:pos"
while read indv
do
    header_hybrid+=`echo $'\t'${indv}`
done < ${hyb_filename}
echo "${header_hybrid}" > ${hybrid_genotype_file}

BO_phased="BO_${scaffold_name}.phased"
SO_phased="SO_${scaffold_name}.phased"
    
for i in ${empirical_markers[@]}
do
    bcftools query -r $i -f '%CHROM:%POS\t\t[\t%GT]\n' "${BO_phased}.vcf.gz" >> ${BO_genotype_file}
    bcftools query -r $i -f '%CHROM:%POS\t\t[\t%GT]\n' "${SO_phased}.vcf.gz" >> ${SO_genotype_file}
    bcftools query -r $i -S ${hyb_filename} -f '%CHROM:%POS\t\t[\t%GT]\n' ${chrom_no_missing} >> ${hybrid_genotype_file}
done
